config/routes.rb
Cdms::Application.routes.draw do

  root :to => "home#index"

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/password/edit' => 'devise/registrations#edit'
  end

  resources :employees

  resources :products

  resources :treatments

  resources :branches

  get "home/index"

end

app/models/treatment.rb
class Treatment < ActiveRecord::Base

	validates :treatment_id, :presence => { :message => " ID can not be left blank" }, :uniqueness => { :message => " must be unique" }

	validates :name, :presence => { :message => " can not be left blank" } 

	validates :description, :presence => { :message => " can not be left blank" } 

	validates :time_period, :presence => { :message => " can not be left blank" } 

	validates :status, :presence => { :message => " can not be left blank" } 

	validates :pricing, :presence => { :message => " can not be left blank" } 

	validates :price, :presence => { :message => " can not be left blank" } 

   # Setup accessible (or protected) attributes for your model
attr_accessible :treatment_id, :name, :description, :time_period, :status, :pricing, :base_time, :price, :priority, :taxable


end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
 #  load_and_authorize_resource

  # GET /treatments
  # GET /treatments.json
  def index
    @treatments = Treatment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @treatments }
    end
  end

  # GET /treatments/1
  # GET /treatments/1.json
  def show
    @treatment = Treatment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @treatment }
    end
  end

  # GET /treatments/new
  # GET /treatments/new.json
  def new
    @treatment = Treatment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @treatment }
    end
  end

  # GET /treatments/1/edit
  def edit
    @treatment = Treatment.find(params[:id])
  end

  # POST /treatments
  # POST /treatments.json
  def create
    @treatment = Treatment.new(params[:treatment])

    respond_to do |format|
      if @treatment.save
        format.html { redirect_to @treatment, notice: 'Treatment was successfully created.' }
        format.json { render json: @treatment, status: :created, location: @treatment }
      else
        format.html { render action: "new" }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /treatments/1
  # PUT /treatments/1.json
  def update
    @treatment = Treatment.find(params[:id])

    respond_to do |format|
      if @treatment.update_attributes(params[:treatment])
        format.html { redirect_to @treatment, notice: 'Treatment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treatments/1
  # DELETE /treatments/1.json
  def destroy
    @treatment = Treatment.find(params[:id])
    @treatment.destroy

    respond_to do |format|
      format.html { redirect_to treatments_url }
      format.json { head :ok }
    end
  end
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/treatments/_form.html.erb
<%= simple_form_for(@treatment) do |f| %>
  <% if @treatment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@treatment.errors.count, "error") %> prohibited this treament from being saved:</h2>

      <ul>
      <% @treatment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form id="f1 box">
			<div class="block">
				<div id="innerblock_left">
					<%= f.label :Treatment_ID, :class =>"label_name", :label => "Treatment ID", :required => true %>
					<span class="style2" type="text" name="n2">
				    		<%= f.text_field :treatment_id, :class => "style2" %>
					</span>
				</div>
				<div id="innerblock_right">
					<%= f.label :Name, :class =>"label_name", :required => true %>
					<span class="style2" type="text" name="n2">
				    		<%= f.text_field :name, :class => "style2", :placeholder => 'Name of treatment' %>
					</span>
				</div>
		   </div>
			<div class="block">
				<div id="innerblock_left">
    					<%= f.input :priority, :label_html => { :class => 'label_name' }, :input_html => { :class => 'style2' }, :label => "Priority" , :collection => [["Level 1"], ["Level 2"],["Level 3"], ["Level 4"],["Level 5"], ["Level 6"],["Level 7"], ["Level 8"],["Level 9"], ["Level 10"]], :include_blank => false %>
				</div>
				<div id="innerblock_right">
    					<%= f.label :time_period, :class =>"label_name", :label => "Time Period", :required => true %>
					<span class="style2">
    						<%= f.text_field :time_period, :class => "style2" %>
					</span>
				</div>
		   </div>
			<div class="block">
					<div id="innerblock_left">
						<div>
    							<%= f.input :status, :label_html => { :class => 'label_name' }, :input_html => { :class => 'style2' }, :label => "Status" , :collection => [["Available"], ["Stopped"]], :include_blank => false, :required => true %>
						</div>
						<div id="innerblock_left_sub" >
    							<%= f.input :pricing, :label_html => { :class => 'label_name' }, :input_html => { :class => 'style2' }, :label => "Pricing" , :collection => [["Head Office Management"], ["Branch Office Management"]], :include_blank => false, :required => true %>

						</div>
					</div>
					<div id="innerblock_right">
						<%= f.label :Description, :class =>"label_name", :required => true  %>
						<span class="style2">
    							<%= f.text_area :description, :rows => 8, :cols => 30, :class => "style1"  %>
						</span>
					</div>
			</div>
			<div class="block">
				<div id="innerblock_left">
					<%= f.label :Base_Time, :class =>"label_name" %>
					<span class="style2" type="text" name="n2">
				    		<%= f.text_field :base_time, :class => "style2"%>
					</span>
				</div>
				<div id="innerblock_right">
    					<%= f.label :price, :class =>"label_name", :label => "Price", :required => true %>
					<span class="style2">
    						<%= f.text_field :price, :class => "style2" %>
					</span>
				</div>
		   </div>
			<div class="block">
				<div id="innerblock_left">
     					<%= f.label :taxable, :class =>"label_name", :label => "Taxable" %>
					<span class="style2">
    						<%= f.check_box :taxable %>
					</span>
				</div>
		   </div>
			
			<div class="block  block_bt">
				<span>
					<input class="style3" type="submit" value="Add Treatment" name="n10"  >
				</span>
				<span>
					<input class="style3" type="submit" value="Cancel" name="n10" >
				</span>
			</div>
		</form>

<% end %>

app/views/treatments/edit.html.erb
<div class="header_bg">
	<h2>Editing treatment </h2>
</div>

<%= render 'form' %>

<%= link_to 'Show', @treatment %> |
<%= link_to 'Back', treatments_path %>

app/views/treatments/index.html.erb
		<div class="header_bg">
			<h2> Treatment List </h2>
			
		</div>
		<div class="branch_button">
		
		<img src="../images/search.png" width="153" height="35" border="none"/>
	   <a href="treatments/new.html">
		<img src="../images/addbutton.png" width="128" height="40" border="none"/></a>
		<a href="#">
		<img src="../images/editbutton.png" width="128" height="39" border="none" onClick='alert("Please select a treatment to edit")'/>
		</a></div>
		<div class="branch_text"> <a href="default.asp">Advanced Search</a></div>


<table class="index_box">
  <tr>
    <th class="maintitle user_radio bg_listholder"></th>
    <th class="maintitle bg_listholder">ID</th>
    <th class="maintitle bg_listholder">Treatment Name</th>
    <th class="maintitle bg_listholder">Price</th>
    <th class="maintitle bg_listholder">Description</th>
    <th class="maintitle bg_listholder">Taxable</th>
  </tr>


<% @treatments.each do |treatment| %>
  <tr class="<%= cycle('title', 'bg_grey') %> ">
    <td class="user_radio"><%= radio_button_tag("treatment_ids[]", treatment.id, false, :onClick => 'location.href="' + edit_treatment_path(treatment) + '"'
)%></td>
    <td class="user_id" id="bg_listholder"><%= treatment.id %></td>
    <td class="treatment_name" id="bg_listholder"><%= treatment.name %></td>
    <td class="treatment_price" id="bg_listholder"><%= treatment.price %></td>
    <td class="treatment_description" id="bg_listholder"><%= treatment.description %></td>
    <% if treatment.taxable == true %>
				<td class="user_status" id="bg_listholder"><img src="../images/tick.png" width="31" height="34"/></li>
			<% elsif %>
				<td class="user_status" id="bg_listholder"><img src="../images/untick.png" width="31" height="34"/></li>
   <% end %>
  </tr>

<% end %>
</table>

app/views/treatments/new.html.erb
<div class="header_bg">
	<h2> Add a new treatment </h2>
</div>

<%= render 'form' %>

<%= link_to 'Back', treatments_path %>

app/views/treatments/show.html.erb
		<div class="header_bg">
			<h2> Treatment View </h2>
		</div>
		<form>
			<div class="block">
				<div id="innerblock_left">

					<label class="label_name">Treatment name </label>
					<div class="style2 style4">
					 :<%= @treatment.name%>						
					</div>
				</div>	
						
					
				<div id="innerblock_right" style="margin-left:28px;">
					<label class="label_name">Treatment Description</label>
					<span class="style2">
						:<%= @treatment.description%>
					</span>
				</div>
		   </div>
			<div class="block">
					<div id="innerblock_left">
						<div>
							<label class="label_name">Time period</label>
							<span class="style2">
								:<%= @treatment.time_period%>
							</span>
						</div>
						
					</div>
					<div id="innerblock_right">
						<label class="label_name">Status</label>
						<span class="style2">
							:<%= @treatment.status%>
						</span>
				  </div>
			</div>
			<div class="block">
				<div id="innerblock_left">
						
							<label class="label_name">Pricing</label>
							<span class="style2">
								:<%= @treatment.pricing%>
							</span>
					
						
					</div>
				<div id="innerblock_right">
					<label class="label_name">Base time</label>
					<span class="style2">
						:<%= @treatment.base_time%>
					</span>
				</div>
			</div>
			<div class="block">
				<div id="innerblock_left">

							<label class="label_name">Price</label>
							<span class="style2">
							
							:<%= @treatment.price%>			
							</span>	
						
						
					</div>
				<div id="innerblock_right" style="margin-left: 33px;">
					<label class="label_name">Priority</label>
					<span class="style2">
						:<%= @treatment.priority%>	
					</span>	
				</div>
			</div>

			<div class="block_bt">
				<span>
			<% if can? :update, @treatment %>
			<%= button_to 'Edit treatment', edit_treatment_path(@treatment), :type => "submit", :class => "style3", :method => "get" %>
			<% end %>
				</span>
				<span>
			<% if can? :read, @treatment %>
			<%= button_to 'Back', treatments_path, :type => "submit", :class => "style3", :method => "get" %>
			<% end %>
				</span>
			</div>
		</form>