config/routes.rb
Cdms::Application.routes.draw do

  root :to => "home#index"

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/password/edit' => 'devise/registrations#edit'
  end

  resources :employees

  resources :products

  resources :treatments

  resources :branches

  get "home/index"

end

app/models/branch.rb
class Branch < ActiveRecord::Base

	validates :branch_id, :presence => { :message => " ID can not be left blank" }, :uniqueness => { :message => " ID must be unique" }

	validates :name, :presence => { :message => " can not be left blank" }, :length => { :in => 2..40, :message => " of Branch must be between 2 to 40 charachters long" }

	validates :phone, :presence => { :message => " can not be left blank" },:numericality => { :only_integer => true, :message => " can only consist of digits" }, :length => { :is => 10, :message => " must be 10 digits long" }

	validates :address, :presence => { :message => " can not be left blank" }

	validates :alternate, :numericality => { :only_integer => true, :message => " alternate number can only consist of digits" }, :length => { :is => 10, :message => " alternate number must be 10 digits long" }, :allow_blank => true

	validates :operationstartdate, :presence => { :message => " please select a date" } 

  # Setup accessible (or protected) attributes for your model
  attr_accessible :branch_id, :name, :description, :address, :phone, :alternate, :pricing, :online, :active, :operationstartdate, :comments

end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
 # load_and_authorize_resource

  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @branches }
    end
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
    @branch = Branch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @branch }
    end
  end

  # GET /branches/new
  # GET /branches/new.json
  def new
    @branch = Branch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @branch }
    end
  end

  # GET /branches/1/edit
  def edit
    @branch = Branch.find(params[:id])
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(params[:branch])

    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
        format.json { render json: @branch, status: :created, location: @branch }
      else
        format.html { render action: "new" }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /branches/1
  # PUT /branches/1.json
  def update
    @branch = Branch.find(params[:id])

    respond_to do |format|
      if @branch.update_attributes(params[:branch])
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch = Branch.find(params[:id])
    @branch.destroy

    respond_to do |format|
      format.html { redirect_to branches_url }
      format.json { head :ok }
    end
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<%= simple_form_for(@branch) do |f| %>
  <% if @branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
      <% @branch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form id="f1 box">

			<div class="block">
				<div id="innerblock_left">
					<%= f.label :Branch_Id, :class =>"label_name", :required => true %>
					<span class="style2" type="text" name="n2">
				    		<%= f.text_field :branch_id, :class => "style2" %>
					</span>
				</div>
				<div id="innerblock_right">
					<%= f.label :Name, :class =>"label_name", :required => true %>
					<span class="style2" type="text" name="n2">
				    		<%= f.text_field :name, :class => "style2", :placeholder => 'Name of branch' %>
					</span>
				</div>
		   </div>


			<div class="block">
				<div id="innerblock_left">
    					<%= f.label :Phone_Number, :class =>"label_name", :label => "Phone Number", :required => true %>
					<span class="style2">
    						<%= f.text_field :phone, :class => "style2" %>
					</span>
				</div>
				<div id="innerblock_right">
					<%= f.label :Alternate_Phone, :class =>"label_name", :label => "Alternate Number"   %>
					<span class="style2">
						<%= f.text_field :alternate, :class => "style2" %>
					</span>
				</div>
		   </div>
			<div class="block">
					<div id="innerblock_left">
						<div>
		    					<%= f.label :Operation_Started_On, :class =>"label_name" , :label => "Operation Started On"  %>
							<span class="style2">
    								<%= f.date_select :operationstartdate, :class => "style2" %>
							</span>
						</div>
						<div id="innerblock_left_sub" >
					<%= f.input :pricing, :label_html => { :class => 'label_name' }, :label => "Pricing Category" , :collection => [["Head Office Management"], ["Branch Office Management"]], :include_blank => false %> 
						</div>
					</div>
					<div id="innerblock_right">
						<%= f.label :Description, :class =>"label_name"  %>
						<span class="style2">
    							<%= f.text_area :description, :rows => 8, :cols => 30, :class => "style1"  %>
						</span>
					</div>
			</div>
			<div class="block">
				<div id="innerblock_left">
    					<%= f.label :Online_Branch, :class =>"label_name", :label => "Online Branch"   %>
					<span class="style2" >
    						<%= f.check_box :online, :class => "style5" %>
					</span>
				</div>
					<div id="innerblock_right">
						<%= f.label :active, :class =>"label_name"   %>
						<span class="style2" >
    							<%= f.check_box :active, :class => "style5" %>
						</span>
					</div>
			</div>
			<div class="block">
				<div id="innerblock_left">
    					<%= f.label :Address, :class =>"label_name", :required => true %>
					<span class="style2">
    						<%= f.text_area :address, :rows => 8, :cols => 30, :class => "style1" %>
					</span>
				</div>

				<div id="innerblock_right">
    					<%= f.label :Comments, :class =>"label_name"  %>
					<span class="style2">
    						<%= f.text_area :comments, :rows => 8, :cols => 30, :class => "style1"  %>
					</span>
				</div>
				</div>

				<div class="block">
				</div>
			<div class="block  block_bt">
				<span>
					<input class="style3" type="submit" value="Add Branch" name="n10"  >
				</span>
				<span>
					<input class="style3" type="submit" value="Cancel" name="n10" >
				</span>
			</div>
		</form>

<% end %>

app/views/branches/edit.html.erb
<div class="header_bg">
	<h2>Editing branch </h2>
</div>

<%= render 'form' %>

<%= link_to 'Show', @branch %> |
<%= link_to 'Back', branches_path %>

app/views/branches/index.html.erb
		<div class="header_bg">
			<h2> Branch List </h2>
			
		</div>
		<div class="branch_button">
		
		<img src="../images/search.png" width="153" height="35" border="none"/>
	   <a href="branches/new.html">
		<img src="../images/addbutton.png" width="128" height="40" border="none"/></a>
		<a href="#">
		<img src="../images/editbutton.png" width="128" height="39" border="none" onClick='alert("Please select a branch to edit")'/>
		</a></div>
		<div class="branch_text"> <a href="default.asp">Advanced Search</a></div>


<table class="index_box">
  <tr>
    <th class="maintitle user_radio bg_listholder"></th>
    <th class="maintitle bg_listholder">ID</th>
    <th class="maintitle bg_listholder">Branch Name</th>
    <th class="maintitle bg_listholder">Address</th>
    <th class="maintitle bg_listholder">Phone Number</th>
    <th class="maintitle bg_listholder">Status</th>
  </tr>


<% @branches.each do |branch| %>
  <tr class="<%= cycle('title', 'bg_grey') %> ">
    <td class="user_radio"><%= radio_button_tag("branch_ids[]", branch.id, false, :onClick => 'location.href="' + edit_branch_path(branch) + '"'
)%></td>
    <td class="branch_id" id="bg_listholder"><%= branch.id %></td>
    <td class="branch_name" id="bg_listholder"><%= branch.name %></td>
    <td class="branch_address" id="bg_listholder"><%= branch.address %></td>
    <td class="branch_number" id="bg_listholder"><%= branch.phone %></td>
    <% if branch.active == true %>
				<td class="user_status" id="bg_listholder"><img src="../images/tick.png" width="31" height="34"/></li>
			<% elsif %>
				<td class="user_status" id="bg_listholder"><img src="../images/untick.png" width="31" height="34"/></li>
   <% end %>
  </tr>

<% end %>
</table>

app/views/branches/new.html.erb
<div class="header_bg">
	<h2> Add a new branch </h2>
</div>

<%= render 'form' %>

<%= link_to 'Back', branches_path %>

app/views/branches/show.html.erb
			<p id="notice"><%= notice %></p>

			<div class="block">
				<div id="innerblock_left">
					<p class="label_name">Name</p>
					<span class="style2">
						<%= @branch.name %>
					</span>
				</div>
				<div id="innerblock_right">
					<p class="label_name">Phone Number</p>
					<span class="style2">
						<%= @branch.phone %>
					</span>
				</div>
		   </div>
			<div class="block">
					<div id="innerblock_left">
						<div>
						<p class="label_name">Alternate Number</p>
							<span class="style2">
							<%= @branch.alternate %>
							</span>
						</div>
						<div id="innerblock_left_sub" >
						<p class="label_name">Pricing category</p>
							<span class="style2" >
								<%= @branch.pricing %>
							</span>
						</div>
					</div>
					<div id="innerblock_right">
					<p class="label_name">Decription</p>
						<span class="style2">
							<%= @branch.description %>
						</span>
					</div>
			</div>
			<div class="block">
				<div id="innerblock_left">
					<p class="label_name">Online</p>
					<span class="style2" >
						<%= @branch.online %>
					</span>
				</div>
				<div id="innerblock_right">
					<p class="label_name">Operation start date</p>
					<span class="style2">
						<%= @branch.operationstartdate %>
					</span>
				</div>
			</div>
			<div class="block">
				<div id="innerblock_left">
					<p class="label_name">Address</p>
					<span class="style2">
						<%= @branch.address %>
					</span>
				</div>
					
				<div id="innerblock_right">
					<p class="label_name">Comments</p>
					<span class="style2">
						<%= @branch.address %>
					</span>
				</div>
				</div>

				<div class="block">
					<p class="label_name">Active</p>
					<span class="style2">
						<%= @branch.active %>
					</span>
				</div>


			<div class="block  block_bt">
				<span>
			<% if can? :update, @branch %>
			<%= button_to 'Edit Branch', edit_branch_path(@branch), :type => "submit", :class => "style3", :method => "get" %>
			<% end %>
				</span>
				<span>
			<% if can? :read, @branch %>
			<%= button_to 'Back', branches_path, :type => "submit", :class => "style3", :method => "get" %>
			<% end %>
				</span>
			</div>