config/routes.rb
Cdms::Application.routes.draw do

  root :to => "home#index"

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/password/edit' => 'devise/registrations#edit'
  end

  resources :employees

  resources :products

  resources :treatments

  resources :branches

  get "home/index"

end

app/models/employee.rb
class Employee < ActiveRecord::Base

	validates :employeeid, :presence => { :message => " can not be left blank" }, :uniqueness => { :message => " must be unique" }
        
	validates :title, :presence => { :message => " can not be left blank" } 
	
	validates :fore_name, :presence => { :message => " can not be left blank" }, :length => { :in => 2..40, :message => " must be between 2 to 40 charachters long" }

	validates :sur_name, :presence => { :message => " can not be left blank" }, :length => { :in => 2..40, :message => " must be between 2 to 40 charachters long" }

	validates :known_as, :presence => { :message => " can not be left blank" }, :length => { :in => 2..40, :message => " must be between 2 to 40 charachters long" }

	validates :date_of_birth, :presence => { :message => " please select the date of birth" } 

	validates :sex, :presence => { :message => ": please select gender" } 	

	validates :job_title, :presence => { :message => " can not be left blank" } 	

	validates :postcode, :presence => { :message => " can not be left blank" }, :length => { :is => 6, :message => " must be 6 characters long" }

	validates :date_of_joining, :presence => { :message => " can not be left blank" } 	

	validates :status, :presence => { :message => " can not be left blank" } 	

  # Setup accessible (or protected) attributes for your model
attr_accessible :employeeid, :title, :fore_name, :sur_name, :known_as, :date_of_birth, :sex, :phone, :mobile_number, :job_title, :address_line_one, :address_line_two, :address_line_three, :address_line_four, :postcode, :email_address, :date_of_joining, :comments, :status

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
 #  load_and_authorize_resource

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :ok }
    end
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= simple_form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form id="f1 box">
			<div class="block">
				<div id="innerblock_left">
					<%= f.label :employeeid, :class =>"label_name", :label => "Employee ID", :required => true %>
					<span class="style2" type="text" name="n2">
				    		<%= f.text_field :employeeid, :class => "style2" %>
					</span>
				</div>
				<div id="innerblock_right">
    					<%= f.input :title, :label_html => { :class => 'label_name' }, :input_html => { :class => 'style2' }, :label => "Title" , :collection => [["Mr."], ["Mrs."]], :include_blank => false %> 
				</div>
		   </div>
			<div class="block">
				<div id="innerblock_left">
					<%= f.label :Fore_Name, :class =>"label_name", :label => "Fore Name", :required => true %>
					<span class="style2" type="text" name="n2">
				    		<%= f.text_field :fore_name, :class => "style2" %>
					</span>
				</div>
				<div id="innerblock_right">
    					<%= f.label :Sur_Name, :class =>"label_name", :label => "Sur Name", :required => true %>
					<span class="style2">
    						<%= f.text_field :sur_name, :class => "style2" %>
					</span>
				</div>
		   </div>
			<div class="block">
				<div id="innerblock_left">
					<%= f.label :known_as, :class =>"label_name", :label => "Known As", :required => true %>
					<span class="style2" type="text" name="n2">
				    		<%= f.text_field :known_as, :class => "style2" %>
					</span>
				</div>
				<div id="innerblock_right">
    					<%= f.label :Date_Of_Birth, :class =>"label_name" , :label => "Date Of Birth", :required => true  %>
					<span class="style2">
    						<%= f.date_select :date_of_birth, :class => "style2" %>
					</span>
				</div>
		   </div>
			<div class="block">
				<div id="innerblock_left">
    					<%= f.input :sex, :label_html => { :class => 'label_name' }, :input_html => { :class => 'style2' }, :label => "Gender" , :collection => [["Male"], ["Female"]], :include_blank => false %>
				</div>
				<div id="innerblock_right">
    					<%= f.label :Phone, :class =>"label_name", :label => "Phone" %>
					<span class="style2">
    						<%= f.text_field :phone, :class => "style2" %>
					</span>
				</div>
		   </div>
			<div class="block">
				<div id="innerblock_left">
					<%= f.label :mobile_number, :class =>"label_name", :label => "Mobile Number" %>
					<span class="style2" type="text" name="n2">
				    		<%= f.text_field :mobile_number, :class => "style2" %>
					</span>
				</div>
				<div id="innerblock_right">
    					<%= f.input :job_title, :label_html => { :class => 'label_name' }, :input_html => { :class => 'style2' }, :label => "Job Title" , :collection => [["Branch manager"], ["Regional Head"]], :include_blank => false %>
				</div>
		   </div>
			<div class="block">
				<div id="innerblock_left">
					<%= f.label :Address_Line_One, :class =>"label_name", :label => "Address Line One" %>
					<span class="style2" type="text" name="n2">
				    		<%= f.text_field :address_line_one, :class => "style2" %>
					</span>
				</div>
				<div id="innerblock_right">
    					<%= f.label :Address_Line_Two, :class =>"label_name", :label => "Address Line Two" %>
					<span class="style2">
    						<%= f.text_field :address_line_two, :class => "style2" %>
					</span>
				</div>
		   </div>
			<div class="block">
				<div id="innerblock_left">
					<%= f.label :Address_Line_Three, :class =>"label_name", :label => "Address Line Three" %>
					<span class="style2" type="text" name="n2">
				    		<%= f.text_field :address_line_three, :class => "style2" %>
					</span>
				</div>
				<div id="innerblock_right">
    					<%= f.label :Address_Line_Four, :class =>"label_name", :label => "Address Line Four" %>
					<span class="style2">
    						<%= f.text_field :address_line_four, :class => "style2" %>
					</span>
				</div>
		   </div>

			<div class="block">
				<div id="innerblock_left">
					<%= f.label :PostCode, :class =>"label_name", :label => "Postcode", :required => true %>
					<span class="style2" type="text" name="n2">
				    		<%= f.text_field :postcode, :class => "style2" %>
					</span>
				</div>
				<div id="innerblock_right">
    					<%= f.label :Email_Address, :class =>"label_name", :label => "Email Address", :required => true %>
					<span class="style2">
    						<%= f.text_field :email_address, :class => "style2" %>
					</span>
				</div>
		   </div>
			<div class="block">
				<div id="innerblock_left">
    					<%= f.label :Date_Of_Joining, :class =>"label_name" , :label => "Date Of Joining", :required => true  %>
					<span class="style2">
    						<%= f.date_select :date_of_joining, :class => "style2" %>
					</span>
				</div>
				<div id="innerblock_right">
    					<%= f.input :status, :label_html => { :class => 'label_name' }, :input_html => { :class => 'style2' }, :label => "Status" , :collection => [["Active"], ["Inactive"], ["Deleted"]], :include_blank => false %>
				</div>
		   </div>
			
			
			<div class="block">
				<div id="innerblock_left">
					<%= f.label :comments, :class =>"label_name", :label => "Comments" %>
					<span class="style2">
    							<%= f.text_area :comments, :rows => 8, :cols => 30, :class => "style1"  %>
						</span>
				</div>
				
		   </div>
			
			<div class="block  block_bt">
				<span>
					<input class="style3" type="submit" value="Add Treatment" name="n10"  >
				</span>
				<span>
					<input class="style3" type="submit" value="Cancel" name="n10" >
				</span>
			</div>
		</form>
<% end %>

app/views/employees/edit.html.erb
<div class="header_bg">
	<h2>Editing employee </h2>
</div>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
		<div class="header_bg">
			<h2> Employee List </h2>
			
		</div>
		<div class="branch_button">
		
		<img src="../images/search.png" width="153" height="35" border="none"/>
	   <a href="employees/new.html">
		<img src="../images/addbutton.png" width="128" height="40" border="none"/></a>
		<a href="#">
		<img src="../images/editbutton.png" width="128" height="39" border="none" onClick='alert("Please select a employee to edit")'/>
		</a></div>
		<div class="branch_text"> <a href="default.asp">Advanced Search</a></div>


<table class="index_box">
  <tr>
    <th class="maintitle user_radio bg_listholder"></th>
    <th class="maintitle bg_listholder">ID</th>
    <th class="maintitle bg_listholder">Title</th>
    <th class="maintitle bg_listholder">First Name</th>
    <th class="maintitle bg_listholder">Last Name</th>
    <th class="maintitle bg_listholder">Designation</th>
    <th class="maintitle bg_listholder">Status</th>
  </tr>


<% @employees.each do |employee| %>
  <tr class="<%= cycle('title', 'bg_grey') %> ">
    <td class="user_radio"><%= radio_button_tag("employee_ids[]", employee.id, false, :onClick => 'location.href="' + edit_employee_path(employee) + '"'
)%></td>
    <td class="user_id" id="bg_listholder"><%= employee.id %></td>
    <td class="emp_title" id="bg_listholder"><%= employee.title %></td>
    <td class="emp_firstname" id="bg_listholder"><%= employee.fore_name %></td>
    <td class="emp_lastname" id="bg_listholder"><%= employee.sur_name %></td>
    <td class="emp_designation" id="bg_listholder"><%= employee.job_title %></td>
    <% if employee.status == "true" %>
				<td class="user_status" id="bg_listholder"><img src="../images/tick.png" width="31" height="34"/></li>
			<% elsif %>
				<td class="user_status" id="bg_listholder"><img src="../images/untick.png" width="31" height="34"/></li>
   <% end %>
  </tr>

<% end %>
</table>

app/views/employees/new.html.erb
<div class="header_bg">
	<h2> Add a new employee </h2>
</div>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
		<div class="header_bg">
			<h2> Employee View </h2>
		</div>
		<form>
			<div class="block">
				<div id="innerblock_left">

					<label class="label_name">Employee id </label>
					<div class="style2 style4">
					 :<%= @employee.employeeid %>						
					</div>
				</div>	
						
					
				<div id="innerblock_right" style="margin-left:28px;">
					<label class="label_name">Title</label>
					<span class="style2">
						:<%= @employee.title %>
					</span>
				</div>
		       </div>

			<div class="block">
				<div id="innerblock_left">

					<label class="label_name">Fore Name </label>
					<div class="style2 style4">
					 :<%= @employee.fore_name %>						
					</div>
				</div>	
						
					
				<div id="innerblock_right" style="margin-left:28px;">
					<label class="label_name">Sur Name</label>
					<span class="style2">
						:<%= @employee.sur_name %>
					</span>
				</div>
		       </div>
			<div class="block">
				<div id="innerblock_left">

					<label class="label_name">Known as</label>
					<div class="style2 style4">
					 :<%= @employee.known_as %>						
					</div>
				</div>	
						
					
				<div id="innerblock_right" style="margin-left:28px;">
					<label class="label_name">Date Of Birth</label>
					<span class="style2">
						:<%= @employee.date_of_birth %>
					</span>
				</div>
		       </div>
			
			<div class="block">
				<div id="innerblock_left">

					<label class="label_name">Sex</label>
					<div class="style2 style4">
					 :<%= @employee.sex %>						
					</div>
				</div>	
						
					
				<div id="innerblock_right" style="margin-left:28px;">
					<label class="label_name">Phone</label>
					<span class="style2">
						:<%= @employee.phone %>
					</span>
				</div>
		       </div>

			<div class="block">
				<div id="innerblock_left">

					<label class="label_name">Mobile Number </label>
					<div class="style2 style4">
					 :<%= @employee.mobile_number %>						
					</div>
				</div>	
						
					
				<div id="innerblock_right" style="margin-left:28px;">
					<label class="label_name">Job Title</label>
					<span class="style2">
						:<%= @employee.job_title %>
					</span>
				</div>
		       </div>

			<div class="block">
				<div id="innerblock_left">

					<label class="label_name">Address </label>
					<div class="style2 style4">
					 :<%= @employee.address_line_one +  @employee.address_line_two + @employee.address_line_three + @employee.address_line_four %>						
					</div>
				</div>	
						
					
				<div id="innerblock_right" style="margin-left:28px;">
					<label class="label_name">Post Code</label>
					<span class="style2">
						:<%= @employee.postcode %>
					</span>
				</div>
		       </div>

			<div class="block">
				<div id="innerblock_left">

					<label class="label_name">Email Address</label>
					<div class="style2 style4">
					 :<%= @employee.email_address %>						
					</div>
				</div>	
						
					
				<div id="innerblock_right" style="margin-left:28px;">
					<label class="label_name">Date Of Joining</label>
					<span class="style2">
						:<%= @employee.date_of_joining %>
					</span>
				</div>
		       </div>

			<div class="block">
				<div id="innerblock_left">

					<label class="label_name">Comments</label>
					<div class="style2 style4">
					 :<%= @employee.comments %>						
					</div>
				</div>	
						
					
				<div id="innerblock_right" style="margin-left:28px;">
					<label class="label_name">Status</label>
					<span class="style2">
						:<%= @employee.status %>
					</span>
				</div>
		       </div>
			<div class="block_bt">
				<span>
			<% if can? :update, @employee %>
			<%= button_to 'Edit', edit_employee_path(@employee), :type => "submit", :class => "style3", :method => "get" %>
			<% end %>
				</span>
				<span>
			<% if can? :read, @employee %>
			<%= button_to 'Back', employee_path, :type => "submit", :class => "style3", :method => "get" %>
			<% end %>
				</span>
			</div>
		</form>

<!--

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employee_path %>

-->