config/routes.rb
Cdms::Application.routes.draw do

  root :to => "home#index"

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/password/edit' => 'devise/registrations#edit'
  end

  resources :employees

  resources :products

  resources :treatments

  resources :branches

  get "home/index"

end

app/models/product.rb
class Product < ActiveRecord::Base

	validates :productid, :presence => { :message => " can not be left blank" }, :uniqueness => { :message => " must be unique" }

	validates :name, :presence => { :message => " can not be left blank" }

	validates :unit_price, :presence => { :message => " can not be left blank" }, :numericality => { :message => " must be a number"}

	validates :universal_product_code, :presence => { :message => " can not be left blank" }, :length => { :is => 10, :message => " must be 10 characters long" }

	validates :status, :presence => { :message => " can not be left blank" } 	

  # Setup accessible (or protected) attributes for your model
attr_accessible :productid, :name, :description, :unit_price, :universal_product_code, :available_quantity, :status, :phone, :warning_quantity_level, :low_quantity_level, :priority

end
		

app/controllers/products_controller.rb
class ProductsController < ApplicationController
 #  load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :ok }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form id="f1 box">
			<div class="block">
				<div id="innerblock_left">
					<%= f.label :ProductId, :class =>"label_name", :required => true %>
					<span class="style2" type="text" name="n2">
				    		<%= f.text_field :productid, :class => "style2", :placeholder => 'product id' %>
					</span>
				</div>
				<div id="innerblock_right">
    					<%= f.label :Name, :class =>"label_name", :label => "Name", :required => true %>
					<span class="style2">
    						<%= f.text_field :name, :class => "style2" %>
					</span>
				</div>
		   </div>
			<div class="block">
					<div id="innerblock_left">
						<div>
    							<%= f.label :Unit_Price, :class =>"label_name", :label => "Unit Price", :required => true %>
							<span class="style2">
    								<%= f.text_field :unit_price, :class => "style2" %>
							</span>
						</div>
						<div id="innerblock_left_sub" >
     							<%= f.label :Universal_Product_Code, :class =>"label_name", :label => "Universal Product Code", :required => true %>
							<span class="style2">
    								<%= f.text_field :universal_product_code, :class => "style2" %>
							</span>

						</div>
					</div>
					<div id="innerblock_right">
						<%= f.label :Description, :class =>"label_name"  %>
						<span class="style2">
    							<%= f.text_area :description, :rows => 8, :cols => 30, :class => "style1"  %>
						</span>
					</div>
			</div>
			<div class="block">
				<div id="innerblock_left">
					<%= f.input :priority, :label_html => { :class => 'label_name' }, :input_html => { :class => 'style2' }, :label => "Priority" , :collection => [["Level 1"], ["Level 2"],["Level 3"], ["Level 4"],["Level 5"], ["Level 6"],["Level 7"], ["Level 8"],["Level 9"], ["Level 10"]], :include_blank => false %> 
				</div>
				<div id="innerblock_right">
    					<%= f.input :status, :label_html => { :class => 'label_name' }, :input_html => { :class => 'style2' }, :label => "Status" , :collection => [["Available"], ["Stopped"]], :include_blank => false %> 
				</div>
		   </div>
			<div class="block">
				<div id="innerblock_left">
					<%= f.label :Warning_Quantity_Level, :class =>"label_name" %>
					<span class="style2" type="text" name="n2">
				    		<%= f.text_field :warning_quantity_level, :class => "style2"%>
					</span>
				</div>
				<div id="innerblock_right">
    					<%= f.label :Low_Quantity_Level, :class =>"label_name", :label => "low_quantity_level" %>
					<span class="style2">
    						<%= f.text_field :low_quantity_level, :class => "style2" %>
					</span>
				</div>
		   </div>
			
			<div class="block">
				<div id="innerblock_left">
					<%= f.label :Available_Quantity, :class =>"label_name", :required => true %>
					<span class="style2" type="text" name="n2">
				    		<%= f.text_field :available_quantity, :class => "style2"%>
					</span>
				</div>
				
		   </div>
			
			<div class="block  block_bt">
				<span>
					<input class="style3" type="submit" value="Add Treatment" name="n10"  >
				</span>
				<span>
					<input class="style3" type="submit" value="Cancel" name="n10" >
				</span>
			</div>
		</form>

<% end %>

app/views/products/edit.html.erb
<div class="header_bg">
	<h2>Editing product </h2>
</div>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
		<div class="header_bg">
			<h2> Product List </h2>
			
		</div>
		<div class="branch_button">
		
		<img src="../images/search.png" width="153" height="35" border="none"/>
	   <a href="products/new.html">
		<img src="../images/addbutton.png" width="128" height="40" border="none"/></a>
		<a href="#">
		<img src="../images/editbutton.png" width="128" height="39" border="none" onClick='alert("Please select a product to edit")'/>
		</a></div>
		<div class="branch_text"> <a href="default.asp">Advanced Search</a></div>


<table class="index_box">
  <tr>
    <th class="maintitle user_radio bg_listholder"></th>
    <th class="maintitle bg_listholder">ID</th>
    <th class="maintitle bg_listholder">Product Name</th>
    <th class="maintitle bg_listholder">Available Quantity</th>
    <th class="maintitle bg_listholder">Unit Price</th>
    <th class="maintitle bg_listholder">Status</th>
  </tr>


<% @products.each do |product| %>
  <tr class="<%= cycle('title', 'bg_grey') %> ">
    <td class="user_radio"><%= radio_button_tag("product_ids[]", product.id, false, :onClick => 'location.href="' + edit_product_path(product) + '"'
)%></td>
    <td class="user_id" id="bg_listholder"><%= product.id %></td>
    <td class="product_name" id="bg_listholder"><%= product.name %></td>
    <td class="product_quantity" id="bg_listholder"><%= product.available_quantity %></td>
    <td class="product_price" id="bg_listholder"><%= product.unit_price %></td>
    <% if product.status == "available" %>
				<td class="user_status" id="bg_listholder"><img src="../images/tick.png" width="31" height="34"/></li>
			<% elsif %>
				<td class="user_status" id="bg_listholder"><img src="../images/untick.png" width="31" height="34"/></li>
   <% end %>
  </tr>

<% end %>
</table>

app/views/products/new.html.erb
<div class="header_bg">
	<h2> Add a new product </h2>
</div>
<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
		<div class="header_bg">
			<h2> Product View </h2>
		</div>
		<form>
			<div class="block">
				<div id="innerblock_left">

					<label class="label_name">Product id </label>
					<div class="style2 style4">
					 :<%= @product.productid %>						
					</div>
				</div>	
						
					
				<div id="innerblock_right" style="margin-left:28px;">
					<label class="label_name">Product name</label>
					<span class="style2">
						:<%= @product.name %>
					</span>
				</div>
		   </div>
			<div class="block">
					<div id="innerblock_left">
						<div>
							<label class="label_name">Product Description</label>
							<span class="style2">
								:<%= @product.description %>
							</span>
						</div>
						
					</div>
					<div id="innerblock_right">
						<label class="label_name">Unit Price</label>
						<span class="style2">
							:<%= @product.unit_price %>
						</span>
				  </div>
			</div>
			<div class="block">
				<div id="innerblock_left">
						
							<label class="label_name">Universal Product Code</label>
							<span class="style2">
								:<%= @product.universal_product_code %>
							</span>
					
						
					</div>
				<div id="innerblock_right">
					<label class="label_name">Available Quantity</label>
					<span class="style2">
						:<%= @product.available_quantity %>
					</span>
				</div>
			</div>
			<div class="block">
				<div id="innerblock_left">

							<label class="label_name">Status</label>
							<span class="style2">
							
							:<%= @product.status %>			
							</span>	
						
						
					</div>
				<div id="innerblock_right" style="margin-left: 33px;">
					<label class="label_name">Warning Quantity Level</label>
					<span class="style2">
						:<%= @product.warning_quantity_level %>	
					</span>	
				</div>
			</div>
			<div class="block">
				<div id="innerblock_left">

							<label class="label_name">Low Quantity Level</label>
							<span class="style2">
							
							:<%= @product.low_quantity_level %>			
							</span>	
						
						
					</div>
				<div id="innerblock_right" style="margin-left: 33px;">
					<label class="label_name">Priority</label>
					<span class="style2">
						:<%= @product.priority %>	
					</span>	
				</div>
			</div>

			<div class="block_bt">
				<span>
			<% if can? :update, @product %>
			<%= button_to 'Edit', edit_product_path(@product), :type => "submit", :class => "style3", :method => "get" %>
			<% end %>
				</span>
				<span>
			<% if can? :read, @branch %>
			<%= button_to 'Back', products_path, :type => "submit", :class => "style3", :method => "get" %>
			<% end %>
				</span>
			</div>
		</form>
<!--

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

-->